# For bigger inputs, and fix dropout, keep bn unchanged
MODEL:
    MODEL_UID: "3D_MIL_mc"
    ARCH: "i3d"
    DEPTH: 50
    NUM_CLASSES: 3

DATALOADER:
    TRAIN_CROP_SIZE: [256, 256]
    #TRAIN_CROP_SIZE: [224, 224]
    BATCH_SIZE_PER_GPU: 1
    NUM_WORKERS: 8
    CLIP_RANGE: [0.3, 0.7]

SOLVER:
    LEARNING_RATE: 1e-6
    WEIGHT_DECAY: 0
    WEIGHTS: [1.45648604, 0.45698094, 7.99099099]
    LR_DECAY: 1
    TRAIN_EPOCH: 2000
    SNAPSHOT_FREQ: 10
    SNAPSHOT_HOME: "experiments/MosMed/lr_1e-6_with_weights"
    SNAPSHOT_MODEL_TPL: "ncov_lr_1e-6_with_weights-Epoch_{:05d}_mc.pth"
    LOG_FILE: "experiments/MosMed/lr_1e-6_with_weights/train_MIL_07_11_22_MosMed.log"
    INIT_MODEL_PATH: ""
    INIT_MODEL_STRICT: "True"
    RESUME_EPOCH: 0

DATASETS:
    TRAIN_DATA_ROOT: "./dataset/train_MosMed-seg.text"
    VAL_DATA_ROOT: "./dataset/val_MosMed-seg.text"
    TEST_DATA_ROOT: "./dataset/test_MosMed-seg.text"
    CT_KEYDB: "CT_keydb.json"
