# For bigger inputs, and fix dropout, keep bn unchanged
MODEL:
    MODEL_UID: "3D_MIL_mc"
    ARCH: "i3d"
    DEPTH: 50
    NUM_CLASSES: 3

DATALOADER:
    TRAIN_CROP_SIZE: [256, 256]
    #TRAIN_CROP_SIZE: [224, 224]
    BATCH_SIZE_PER_GPU: 1
    NUM_WORKERS: 10
    CLIP_RANGE: [0.3, 0.7]

SOLVER:
    LEARNING_RATE: 1e-7
    WEIGHT_DECAY: 0
    WEIGHTS: [1.28414097, 0.53048226, 2.9744898]
    LR_DECAY: 1
    TRAIN_EPOCH: 2000
    SNAPSHOT_FREQ: 10
    SNAPSHOT_HOME: "experiments"
    SNAPSHOT_MODEL_TPL: "ncov_lr_1e-7_with_weights-Epoch_{:05d}_mc.pth"
    LOG_FILE: "experiments/train_MIL_27_10_22_lr_1e-7_with_weights.log"
    INIT_MODEL_PATH: ""
    INIT_MODEL_STRICT: "True"
    RESUME_EPOCH: 0

DATASETS:
    TRAIN_DATA_ROOT: "./dataset/train_hust-seg.text"
    VAL_DATA_ROOT: "./dataset/val_hust-seg.text"
    TEST_DATA_ROOT: "./dataset/test_hust-seg.text"
    CT_KEYDB: "CT_keydb.json"
